= StudierendenProjekte 1&2 an der Fachhochschule Nordwestschweiz (FHNW) Informatik & iCompetence

Studierendenprojekte sind ein Markenzeichen der FHNW. 
Alle Studierenden arbeiten in jedem Semester an einem Projekt. 

Gerade im ersten Semester ist das eine Herausforderung, die aber, wie in den Projekten hier ersichtlich, erfolgreich gemeistert wird. 

Die Studierenden hatten die Aufgabe auf einem vorgegebenen Technologiestack eine Simulation oder ein Spiel zu entwickeln. 
Das diesjährige Thema wurde von https://www.primeo-energie.ch/en/ueber-uns/kosmos.html[Primeo Energie Kosmos], einem Science und Erlebnis Center für Klima & Energie in Auftrag gegeben und lautete: 

*Energiespeicherung und Energieverbrauch durch Simulationen und Spiele erlebbar zu machen.*

Die neun Teams bestehend aus je sieben Mitgliedern haben die Herausforderung angenommen und geführt von Dozierenden der FHNW neun Spiel- oder Simulationsideen entwickelt und umgesetzt. 
Wenn alles klappt, werden sie in der einen oder anderen Form im Primeo Energie Kosmos zu sehen sein.

Die Spiele, Anleitung sowie der Code sind nun hier frei verfügbar und wir freuen uns über alle, die Lust haben, eine Idee nachzubauen oder gar weiterzuentwickeln. 

Um die Studierenden bestmöglichst zu unterstützen wurden mehrere Studierendeprojekte in höheren Semestern durchgeführt, die es einfacher machten, https://pi4j.com/[Pi4J]  (auf https://github.com/Pi4J[github]) einzusetzen. 

Im Namen der Studiengangleitung und dem Dozierendenteam, danken wir dem Auftraggeber, dem Team von Pi4J wie auch den Studierenden ganz herzlich für die Arbeit. 



<!--
At FHNW students work on a customer project in every semester. 
This right from the start of their study, which is, admittenly, quite a challenge.

Here you find the result of this challenge. 

The goal was to create simulations and games for the Primeo Kosmos, an educating exhibitions of a local energy provider. 
The students have been working in teams of about seven 
-->



